# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Traffic' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Traffic

  target 'Traffic-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-geocoder', :path => '../node_modules/react-native-geocoder-reborn'

  end

  target 'TrafficTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Traffic-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Traffic-tvOS

  target 'Traffic-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
